/**
 * Even Fibonacci numbers
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

/**
 * @author lschlessinger1
 * 
 */
public class Problem2 {

	public static int getSolution() {
		int sum = 0;

		int fibNMinus2 = 0;
		int fibNMinus1 = 1;
		int fibN = fibNMinus2 + fibNMinus1;

		for (int i = 0; i < 4000000; i++) {
			if (i > fibN) {
				fibNMinus2 = fibNMinus1;
				fibNMinus1 = fibN;
				fibN = fibNMinus2 + fibNMinus1;
			}

			if ((i % 2 == 0) && (i == fibN)) {
				sum += i;
			}
		}
		return sum;
	}
}